import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsInt,
  IsISO8601,
  IsObject,
  IsOptional,
  IsString,
  Length,
  Max,
  Min,
  ValidateNested,
} from 'class-validator';

/**
 * Operational telemetry from the autonomous newsroom.
 *
 * ## Why the shape is this loose, and where it is strict
 *
 * `type` is a plain string rather than an enum. The newsroom owns its event
 * vocabulary — roughly forty names today — and must be able to instrument a new
 * stage without a CMS deployment. Pinning an enum here would make every new
 * event a two-repository change, and the failure mode would be silent telemetry
 * loss rather than a useful error.
 *
 * What *is* strict is size. This endpoint accepts writes from an automated
 * caller at roughly 350 events per newsroom cycle, so an unbounded `metadata`
 * object is the obvious way for one misbehaving emit call to fill a table the
 * live site shares. Hence a byte cap and a depth cap, both checked rather than
 * trusted.
 */

/** Bound on one event's `metadata`, serialised. */
export const MAX_METADATA_BYTES = 4_096;

/**
 * How deeply `metadata` may nest.
 *
 * Telemetry is counts, reasons and scores — flat or nearly so. Anything deeper
 * is a research report or a payload that wandered in, and neither belongs here:
 * the editorial records live in the newsroom's own database and are referenced
 * by id.
 */
export const MAX_METADATA_DEPTH = 3;

/** Events accepted in one request. */
export const MAX_TELEMETRY_BATCH = 200;

export class TelemetryEventDto {
  /**
   * Assigned by the newsroom when the event enters its delivery buffer, and
   * reused on every retry. This is the deduplication mechanism: a redelivered
   * batch collides on the primary key and is skipped.
   */
  @ApiProperty({ description: 'Stable event id generated by the newsroom' })
  @IsString()
  @Length(8, 64)
  id!: string;

  @ApiProperty({ description: 'Event name from the newsroom taxonomy, e.g. RESEARCH_STARTED' })
  @IsString()
  @Length(3, 64)
  type!: string;

  @ApiProperty({ description: 'When the newsroom observed the event (ISO 8601)' })
  @IsISO8601()
  occurredAt!: string;

  @ApiPropertyOptional({ description: 'Correlates every event in one newsroom run' })
  @IsOptional()
  @IsString()
  @Length(1, 64)
  workflowId?: string;

  @ApiPropertyOptional({ description: 'Story cluster in the newsroom database' })
  @IsOptional()
  @IsString()
  @Length(1, 64)
  clusterId?: string;

  @ApiPropertyOptional({ description: 'CMS article id, once one exists' })
  @IsOptional()
  @IsString()
  @Length(1, 64)
  articleId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @Length(1, 48)
  stage?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @Length(1, 48)
  status?: string;

  @ApiPropertyOptional({ description: 'Publisher domain, for source-level events' })
  @IsOptional()
  @IsString()
  @Length(1, 255)
  source?: string;

  @ApiPropertyOptional({ description: 'Model that did the work' })
  @IsOptional()
  @IsString()
  @Length(1, 128)
  model?: string;

  @ApiPropertyOptional({ description: 'Stage duration in milliseconds' })
  @IsOptional()
  @IsInt()
  @Min(0)
  // A day. Past this the value is a bug, not a measurement.
  @Max(86_400_000)
  durationMs?: number;

  @ApiPropertyOptional({ description: `Counts, reasons and scores. Max ${MAX_METADATA_BYTES} bytes` })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}

export class SubmitTelemetryDto {
  @ApiProperty({ type: [TelemetryEventDto], description: `1-${MAX_TELEMETRY_BATCH} events` })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(MAX_TELEMETRY_BATCH)
  @ValidateNested({ each: true })
  @Type(() => TelemetryEventDto)
  events!: TelemetryEventDto[];
}

/**
 * Deepest nesting level in a value, counting the top-level object as 1.
 *
 * Iterative rather than recursive: the input is attacker-shaped by definition —
 * it arrives over HTTP — and a recursive walk over a deliberately deep payload
 * is a stack overflow that takes the API process with it.
 */
export function metadataDepth(value: unknown): number {
  let depth = 0;
  let frontier: unknown[] = [value];

  while (frontier.length > 0) {
    // Only object layers count, so a flat `{ sources: 2 }` is depth 1 rather
    // than 2 — the scalar it holds is not a level of nesting.
    const objects = frontier.filter(item => item !== null && typeof item === 'object');
    if (objects.length === 0) break;

    depth += 1;
    // Past the limit the exact answer stops mattering, and continuing to walk
    // is the work a hostile payload wanted.
    if (depth > MAX_METADATA_DEPTH + 1) return depth;

    frontier = objects.flatMap(item => Object.values(item as Record<string, unknown>));
  }

  return depth;
}
